# Generated by Django 4.1.7 on 2023-04-06 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productoption_unique_together'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='product_attribute_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.productattributeitem'),
        ),
        migrations.DeleteModel(
            name='StockoutProductAttributes',
        ),
    ]
