# Generated by Django 4.1.7 on 2023-04-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('shipping_address', models.TextField(verbose_name='Shipping Address')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('pincode', models.CharField(max_length=10, verbose_name='Pincode')),
            ],
        ),
    ]
