# Generated by Django 4.1.7 on 2023-04-05 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_category_item_alter_category_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('shipping_address', models.TextField(verbose_name='Shipping Address')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('pincode', models.CharField(max_length=10, verbose_name='Pincode')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_due', models.FloatField(default=0.0)),
                ('payment_mode', models.CharField(choices=[('cod', 'Cash On Delivery'), ('money_transffer', 'Money Transffer'), ('online_payment', 'Online Payment')], default='cod', max_length=50)),
                ('payment_status', models.CharField(choices=[('inprogress', 'Inprogress'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('processing', 'Processing'), ('Failed', 'Failed'), ('completed', 'Completed'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded')], default='inprogress', max_length=50)),
                ('shipping_status', models.CharField(choices=[('inprogress', 'Inprogress'), ('returning', 'Returning'), ('returned', 'Returned'), ('shipped', 'Shipped')], default='inprogress', max_length=50)),
                ('shipment_order_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='catalog.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Stockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordered_quantity', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockouts', to='catalog.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
            ],
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='catalog.productattribute'),
        ),
        migrations.CreateModel(
            name='StockoutProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_attribute_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.productattributeitem')),
                ('stockout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.stockout')),
            ],
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockin', to='catalog.product')),
            ],
        ),
    ]
