# Generated by Django 4.1.7 on 2023-04-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_customer_invoice_stockout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='notes',
            field=models.CharField(default='', help_text='Put better notes for future refference.', max_length=255),
        ),
    ]
