# Generated by Django 4.1.7 on 2023-04-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_stockin_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockoutproductattributes',
            name='product_attribute_item',
        ),
        migrations.RemoveField(
            model_name='stockoutproductattributes',
            name='stockout',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryItem',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='StockIn',
        ),
        migrations.DeleteModel(
            name='Stockout',
        ),
        migrations.DeleteModel(
            name='StockoutProductAttributes',
        ),
    ]
