# Generated by Django 4.1.7 on 2023-04-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_invoice_customer_remove_stockin_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together={('product', 'product_attribute')},
        ),
    ]
