# Generated by Django 4.1.7 on 2023-04-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productoption_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
